### ISSUE TITLE
Build an isolated running environment

### ISSUE THREAD

**Issue by mingrammer** [mingrammer/pyreportcard#2]
We should build an isolated environments instead of installing all dependencies, systems on local machine.

We'll build docker environment is made of two parts of pyreportcard web server and mongodb as database server

**Comment by mingrammer** [comment]
WIP

**Comment by addianto** [comment]
Hello. I stumbled upon this project by chance and it looks interesting. Do you mind if I take a shot working on this issue? I would like to use this project for analysing students' work in a programming course I teach at public university.

I plan to create a `Dockerfile` to _containerise_ the `pyreportcard` Web app. Then, I will create a `docker-compose.yml` file to run the app along with MongoDB. How does that sound?

**Comment by mingrammer** [comment]
Sorry for late. But sounds good :)

I'm busy nowaday, so I couldn't care about this project. So I'll continue this project after mid of Jan 2020.

For this issue, feel free to send me a PR :)

**Comment by addianto** [comment]
Thanks for the response and happy new year 2020. 🎊 

> For this issue, feel free to send me a PR :)

Will do. 😃

**Comment by mingrammer** [comment]
Thank you :) Happy new year 2020!! 🎉
