### ISSUE TITLE
Check typing annotation (if any) is valid and detect obvious typing issues using mypy

### ISSUE THREAD

**Issue by xavierhardy** [mingrammer/pyreportcard#20]
Use [mypy](https://github.com/python/mypy) to check types are annotated and valid.

**Comment by mingrammer** [comment]
In python, the type annotation is optional. Should we also check it?

Of course, if there are annotations, it would be worth to check that is valid. But I don't think we should check every existence of annotations for entire codebase.

How do you think about it?

**Comment by xavierhardy** [comment]
I have recently starting more and more Go programming and I subscribe to their way of typing things. Basically in Go, when assigning a variable, you do not need to indicate its type since it is implied in the assignment (if you are assigning a string to a variable, then this variable is a string) which is why you mainly have to define types in function inputs/outputs and structs in Go.

However, just running `mypy` to verify existing annotations and obvious typing mistakes would be a valid approach at first. I'll change the issue title accordingly.
