### ISSUE TITLE
Check YAML files if any

### ISSUE THREAD

**Issue by xavierhardy** [mingrammer/pyreportcard#23]
Run [yamllint](https://github.com/adrienverge/yamllint) to check and score all YAML files in the repository.

**Comment by mingrammer** [comment]
Is it worth for this project?

**Comment by xavierhardy** [comment]
A Python project could be using YAML for its configuration, so I thought so. However, since we have already closed the issue about shell scripts (which are more likely to be used), I think we should close this one as well.
