### ISSUE TITLE
trigger pyreport when code pushed

### ISSUE THREAD

**Issue by Xinkle** [mingrammer/pyreportcard#9]
i think it will be useful if pyreport is triggered when code pushed
like travis ci.

just a little idea.

**Comment by mingrammer** [comment]
Yes, I'm considering the hooking service as you said.

There is a plan for providing it as web service in [A plan board of this project](https://github.com/mingrammer/pyreportcard/projects/1). So, this will be served as hook service like travis.

**Comment by mingrammer** [comment]
So, when finished for v2, I'll make the github integration as reporting tools for python repository
